add regression test framework

diff --git a/6502/Makefile b/6502/Makefile
--- a/6502/Makefile
+++ b/6502/Makefile
@@ -6,12 +6,32 @@ CA65=ca65
 LD65=ld65
 
 
-tests: k6502_test.vcd
+all: k6502_test.vcd
+
+
+.PHONY: tests
+
+ASM_TESTS=${wildcard tests/*.S}
+TXT_TESTS=${ASM_TESTS:.S=.txt}
+TESTS=${ASM_TESTS:.S=}
+
+tests: ${TXT_TESTS}
+	${IVERILOG} -DTRACE -Wall -y. -o k6502_test k6502_test.v
+	@for test in ${TESTS}; do \
+		cp $$test.txt rom.txt; \
+		${VVP} -n ./k6502_test | grep -v "VCD info" > $$test-out.csv; \
+		rm rom.txt; \
+		diff $$test-out.csv $$test-pass.csv > /dev/null; \
+		if [ "$$?" == "0" ]; then \
+			echo "$$test: pass"; \
+		else \
+			echo "$$test: fail"; \
+		fi \
+	done
 
 dumper: dumper.o
 
 %_test: %_test.v
-	${IVERILOG} -Wall -y. -o $@ $<
 
 %.vcd: %
 	${VVP} -n ./$<
